/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.36).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.OS;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-12-01T04:50:02.206Z[GMT]")
@Validated
public interface OsApi {

    @Operation(summary = "Delete OS", description = "", tags={ "OS" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successfully OS deleted", content = @Content(mediaType = "application/json;charset&#x3D;UTF-8", schema = @Schema(implementation = OS.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad syntactic"),
        
        @ApiResponse(responseCode = "404", description = "No such OS found"),
        
        @ApiResponse(responseCode = "500", description = "Internal server error"),
        
        @ApiResponse(responseCode = "504", description = "Gateway timeout") })
    @RequestMapping(value = "/os/{id}",
        produces = { "application/json;charset=UTF-8" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<OS> deleteOSByID(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") Long id);


    @Operation(summary = "Rent OS capability", description = "", tags={ "OS" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successfully", content = @Content(mediaType = "application/json;charset&#x3D;UTF-8", schema = @Schema(implementation = OS.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad syntactic"),
        
        @ApiResponse(responseCode = "404", description = "No such OS found"),
        
        @ApiResponse(responseCode = "500", description = "Internal server error"),
        
        @ApiResponse(responseCode = "504", description = "Gateway timeout") })
    @RequestMapping(value = "/os/{id}",
        produces = { "application/json;charset=UTF-8" }, 
        method = RequestMethod.GET)
    ResponseEntity<OS> getOSByID(@Parameter(in = ParameterIn.PATH, description = "Get OS", required=true, schema=@Schema()) @PathVariable("id") Long id);


    @Operation(summary = "Change OS", description = "", tags={ "OS" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successfully OS changed", content = @Content(mediaType = "application/json;charset&#x3D;UTF-8", schema = @Schema(implementation = OS.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad syntactic"),
        
        @ApiResponse(responseCode = "402", description = "Payment required"),
        
        @ApiResponse(responseCode = "404", description = "No such OS found"),
        
        @ApiResponse(responseCode = "500", description = "Internal server error"),
        
        @ApiResponse(responseCode = "504", description = "Gateway timeout") })
    @RequestMapping(value = "/os/{id}",
        produces = { "application/json;charset=UTF-8" }, 
        method = RequestMethod.POST)
    ResponseEntity<OS> postOSByID(@Parameter(in = ParameterIn.PATH, description = "You can change OS", required=true, schema=@Schema()) @PathVariable("id") Long id);


    @Operation(summary = "Buy OS", description = "", tags={ "OS" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "OS added", content = @Content(mediaType = "application/json;charset&#x3D;UTF-8", schema = @Schema(implementation = OS.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad syntactic"),
        
        @ApiResponse(responseCode = "402", description = "Payment required"),
        
        @ApiResponse(responseCode = "404", description = "No such ip addresses found"),
        
        @ApiResponse(responseCode = "500", description = "Internal server error"),
        
        @ApiResponse(responseCode = "504", description = "Gateway timeout") })
    @RequestMapping(value = "/os/{id}",
        produces = { "application/json;charset=UTF-8" }, 
        method = RequestMethod.PUT)
    ResponseEntity<OS> putOSByID(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") Long id);

}

